### PR TITLE
Add UrlRewriting decorator that can be used to rewrite requests to pe…

### PR DESCRIPTION
**Pull request by dmfs**
…rmanently redirected targets. #12

It takes a RewritePolicy that determines the actual target of a request. This is could also be used to add a default request parameter or to replace http by https on every request.

This also adds a RedirectPolicy which stores all permanent redirects. It can be used in conjunction with SimpleRewritePolicy which reads redirects from the same source.

### CODE REVIEW

**Comment by dmfs** [comment]
I'm not entirely sure if it's correct to have this `UriRewrites` interface. Somehow it doesn't seem right.

Also, with the use cases for this in mind, it's probably not correct to store permanent redirects in a separate database or file. Instead the specs recommend to update the sources of the URL, if possible, see https://tools.ietf.org/html/rfc7238#section-3
So in case of a sync app, it should replace the calendar/address book URL in the respective database instead.

On the other hand, storing all redirects together in a lookup table seems to be a fairly simple approach that should work in most cases.

One thing that's also not covered is multiple permanent redirects. At present it only handles the first one. Though this would certainly be an edge case.

**Comment by lemonboston** [comment]
I am not sure how this works with the uri parameters.. when there is a redirect, does the Location header contains the original parameters, or is that only the base uri or even just the host, and client have to add parameters again?

Another general question I have is, could this be handled by caching as well?
Although, I see that this is a specific, easier subset, kind of, and maybe more efficient this way.
I don't understand the note in the RFC that 308 is cacheable unless otherwise specified in header - how could it not be? If there is any use-case when it's not cacheable, that would mean it's not a permanent redirect, right? And then in case client should not re-link source automatically. So I don't understand that.

Regarding multiple permanent redirects: if I see correctly, those would be stored as well, just current `SimpleRewritePolicy` only looks up the first one..   can that be simply a recursive call there?
Or maybe even better if `UriRewrites` just overrides earlier targetUris if there is a new entry with that uri as source. You know what I mean? :)

> It takes a RewritePolicy that determines the actual target of a request. This is could also be used to add a default request parameter or to replace http by https on every request.

I don't really understand these use-cases... The url parameter relates to the first question. Isn't that something that should be handled generally? Making sure we keep the url parameters.
Would `UriRewrites` implementation 'copy' the parameters?
Also, replacing http by https, isn't that something that a https executor decorator should take care of? Wouldn't it be either one or the other? Can a redirect 'point' from http to https or vice versa?
As you can see, I don't really know enough about the topic, but I am wondering whether we could save this rewrite policy, remove it.

**Comment by dmfs** [comment]
First of all, this is primarily about URL rewrites, which means this executor replaces the target URL with a different one. How this new URL is derived from the old one is subject to the rewrite policy.

There could be one policy which appends a URL parameter to the query. You can see one of the use cases in the SchedJoules Java API client. There is an executor called [Onymous](https://github.com/schedjoules/java-api-client/blob/master/schedjoules-api/src/main/java/com/schedjoules/client/http/Onymous.java) which just adds the user-identifier to every request. The same could be achieved with a `UrlRewriting` decorator and a `RewritePolicy` that appends the parameter.
Note that this use case doesn't involve redirects. It's purely a client side thing.

Permanent redirects are just another use case of URL rewriting. If there is a component which already knows that certain URLs have been redirected permanently, it can rewrite the original URL right away, before even sending the request.

This is different from caching, which serves the response from a local source, whereas a redirect still sends the original network request, just to a different URL.

If a server sends a redirect, a client is not supposed to modify the URL before resending the request to that address. So the location header should contain any URL parameters that are necessary to fulfil the original request.

The "is cacheable unless otherwise specified" issue is certainly mostly about intermediate proxy servers. A server might not want an intermediate proxy to store redirects for various reasons, including privacy concerns. Updating the source of the original URL by the client is no considered caching.

However, after thinking about this, it's probably not a good idea to store all permanent redirects in the same place, because they could be user specific. I'll spend some more time thinking about this.

FYI: redirects can point from https to http and vice versa, but for security reasons a client might choose to not follow these.

**Comment by lemonboston** [comment]
About the use case for adding fix URL parameter, wouldn't that be solved with a dedicated executor decorator like that `Onymous`, using that 'inside' the redirect decorators?
And by the way, this kind of enriching the request, would that make sense to handle that more generally? Like `new UriEnriching(delegate, uriParam)`, `new HeaderEnriching(delegate, header)`. Something like those. Maybe there is a executor decorator already for request decoration, could use that as well for composition. Anyway, not important for this story.

Thanks for the details about caching.

One more thing I thought about is that wouldn't it be better to call `UriRewrites` something like `RedirectStore`? It looks for me that both `UriRewrites` and `RewritePolicy` has semantic meaning of how to do uri rewrites.
`UriRewrites.rewrite(URI originalUri, URI newUri)` implies a directive already for me, while it is only the policy who should decide what to do. So it would be more straighforward for me if there is a store where all permanent redirects are stored, and the policy can use it to look them up and decide based on that.
To put it more clearly possibly, `UriRewrites` name implies a rewrite already or a guaranteed rewrite, while it will be the policy to decide that, at that point it's only a permanent redirect that happened and is being stored. 
So `Permanent` could also be let's say `PermanentRemembering`.

I also thought about the 'wiring' of this solution for a little while, if I see any alternative way, and I haven't found, so it looks like a good idea. Although I am not sure how well it fits with all kinds of http use-case scenarios that I may not be familiar with.

And back to caching, what I was wondering is if we will have that at some point, which will need persistence as well, wouldn't that be easier to just use that? We probably only need to add the header to permanent redirect response in that case. So I am only thinking about it from future maintenance and usage point of view. For example, would the redirects need a separate persistence setup from the cache? If yes, that can complicate the overall setup of the client a bit.
And about implementing caching, would it be possible to do it step-by-step, so start with something simple that doesn't comply to the full RFC, just what we would need?

**Comment by dmfs** [comment]
Actually `UrlRewriting` is more general than your `UrlEnriching` proposal, because it can do any sort of modification to the URL, not just append parameters. 

Anyway, I've come to think that storing permanent redirects in a separate store is probably not a good idea. The only proper solution seems to be to communicate any permanent redirects back to the caller to allow it to update the source of the URL.

So the question is, how can we communicate any permanent redirect back to the caller? If the `Following` decorator is in use the redirect would never be delivered to the caller. Also, the caller can not use the response URL, because it doesn't tell if any redirect was permanent or not.

Two ways come to my mind:

1) inject a response header that tells a special executor decorator to notify the caller of the redirect. Something like this

```java
ResultType result = new PermanentlyRedirecting(executor, new PermanentRedirectCallback() {
    @Override
    public void onRedirect(Uri newUri)
    {
        // update the source of the request uri
    }).execute(requestUri, request);
```

In that case `PermanentlyRedirecting` (bad name, I know) would watch out for a response header like `X-DMFS-REDIRECT-LOCATION` and call the given callback with the value of that header, if any. That header would be added by the `Following` decorator earlier in the chain if the status code indicated a permanent redirect. Care must be taken to add this header only for permanent redirects and if no temporary redirect occurred earlier for the same request. Optionally the header could evaluated by a special response handler.

2) use a "don't follow permanent redirects" policy. Instead catch the exception, update the source and resent the request.

Neither of these options uses URL rewriting.

**Comment by dmfs** [comment]
Instead of a "don't follow permanent redirects" policy, we could add a request header to instruct the `Following` decorator to throw on a permanent redirect. This would allow to make the decision on a per-request basis.

One more option: use two `Following` decorators. The first one has a policy to not follow permanent redirects and lets them pass to the next decorator in the chain. The second one is added by the caller and handles all permanent redirects (by updating the source).

i.e. 
```java
// an executor that follows only temporary redirects
HttpRequestExecutor executor = new Follwing(
                                  new HttpUrlConnectionExecutor(),
                                     new Temporary(new Secure(new FollowRedirectPolicy())));

// somewhere else in the code

// permanent redirects are handled right where the request is made.
ResponseType response = new Following(
                            excecutor,
                            new Notifying(
                                new FollowRedirectPolicy(),
                                new OnRedirectCallback()
                                    {
                                        @Override
                                        public void onRedirect(Uri newUri)
                                        {
                                            // update the source of the request uri
                                        }
                                    })).execute(url, request));
```

Though, this might require a few changes to how the `Following` decorator works, because in case of a permanent redirect it probably should not throw.

**Comment by lemonboston** [comment]
I am trying to imagine a concrete complete use-case and handling of this, could you please help me with an example?
I mean for example a sync client configured for a target uri notices a permanent redirect. Then what would you like it to do ideally? Rewrite the uri in its configuration somehow? Or notify you with a network call, so you can update the general configuration for all future clients of that provider and maybe sync that back to current clients?

If updating configuration url automatically, how is that stored, is it possible to implement update it generally, let's say in that `onRedirect()` callback above?

**Comment by dmfs** [comment]
In case of our sync clients, there are many URLs, each one stored in a specific location:

* the discovery entry point (whatever the user entered or our API returned for a service) is stored in the account settings
* the principal URL and calendar/addressbook home is stored in the respective provider syncstate column
* the actual calendar and addressbook urls are stored in the respective calendar/addressbook rows.

So whenever a request to one of these results in a redirect the respective database entry would be updated. We wouldn't send anything back to our API though.

Consider a server would send a permanent redirect for the calendar-home URL. In that case the client would update the value in the sync-state and continue using the new value from the next sync on.

**Comment by dmfs** [comment]
In any case it probably makes sense to leave the decision if a redirect is handled by a RedirectPolicy to that policy. At present it's determined by `Following` which means there are only two options:
* Follow
* Fail

The third option 

* Ignore (and pass the response to the next decorator)

is not possible yet. But it would be nice to have for a more fine grained control.

**Comment by dmfs** [comment]
ignoring redirects is subject to #43

**Comment by dmfs** [comment]
I've removed everything that relates to redirects and trimmed it to the bare minimum of rewriting URLs. Communicating permanent redirects to the caller will be subject to a new story.
@lemonboston please review again

**Pull request merged**
