### PR TITLE
Add Apache license template to settings and make it the default.

### LINKED ISSUE #4: Branded executor tests fail
```
/home/marten/IdeaProjects/http-client-essentials-suite/http-executor-decorators/src/test/java/org/dmfs/httpessentials/executors/useragent/UserAgentHeaderDecorationTest.java:32: error: cannot find symbol
import static org.dmfs.httpessentials.executors.useragent.UserAgentHeaderDecoration.USER_AGENT_HEADER;
^
  symbol:   static USER_AGENT_HEADER
  location: class
```

### PR DESCRIPTION
**Pull request by dmfs**
Fixes #4

### CODE REVIEW

**Comment by lemonboston** [comment]
Notes:

- (minor) The '(c)' after 'Copyright' is not needed as per http://www.apache.org/licenses/LICENSE-2.0

- (minor) I don't know if *.iml files are needed under version control in general (I usually ignored them for Android projects) and why they change here specifically. I replicated the update to the copyright folder and only misc.xml changed for me as a result. But I guess we can gitignore them anytime later if needed, so it's not important.

Looks okay for me and IntelliJ found and applied the Apache copyright automatically as expected.

**Comment by dmfs** [comment]
Good point. The .gitignore file is based on some template for IntelliJ. Looks like the Android Studio templates for .gitignore don't include *.iml files and some directories in .idea.

**Comment by dmfs** [comment]
@lemonboston please review again.

**Comment by lemonboston** [comment]
Checked, looks good, .iml files disappeared.

**Comment by dmfs** [comment]
Removing iml files just broke the project in my IDE. It can't open the modules anymore :-(

**Comment by dmfs** [comment]
According to this: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems the iml files need to be shared.

**Pull request merged**
