### PR TITLE
Fix StringLink by implementing relationTypes() and reverseRelationTyp…

### LINKED ISSUE #31: StringLink doesn't return reltypes

### PR DESCRIPTION
**Pull request by dmfs**
…es(). fixes #31 
@lemonboston please review.

### CODE REVIEW

**Comment by lemonboston** [comment]
I am checking the quoted string part, trying to compare it with the RFC and have a few questions.
https://tools.ietf.org/html/rfc2616#section-2.1
```
quoted-string  = ( <"> *(qdtext | quoted-pair ) <"> )
qdtext         = <any TEXT except <">>

The backslash character ("\") MAY be used as a single-character
quoting mechanism only within quoted-string and comment constructs.

quoted-pair    = "\" CHAR
```

It says `qdtext` can't contain `"`, should then `Quoted.value()` throw if it contains `"` in the 'body'?
And `OptionalQuoted.value()` would replace it with something, and `valueString()` methods would handle simirarily.
Why is the escaping and unescaping of backslash and double-quote needed?
Does it relate to the `quoted-string` specs or general http strings handling in java? Could it be separate decorator?
I think unit tests for these 2 classes could be useful (maybe loading values from a text resource file, cause all those escaping in java makes it harder to see the actual strings).

**Comment by lemonboston** [comment]
Shouldn't `QuotedStringConverter` be removed to remove code duplication and use 
`new OptionallyQuoted(PlainStringHeaderConverter.INSTANCE)` instead?

**Comment by lemonboston** [comment]
Could `rel` and `rev` parameter types be `ParameterType<Set<String>>` right away, so no need for the splitting in `Link` implementation? Splitting/joining with a delimeter could be another `EntityConverter` decorator.

**Comment by lemonboston** [comment]
`assertEquals("", new StringLink("<test>").title());`
Docs say `null` should be returned.

Finished the review.

Just a note: I can see now better how much the design of these `Entity`, `EntityValue`, `Parameter`, etc types help reuse and how much they are essential for the http lib.

**Comment by dmfs** [comment]
Good points.

`qdtext` can not contain `"`, but `quoted-string` can contain escaped `"`, that is all occurrences of `"` and `\` have to be escaped. Which should answer the 2nd question.

Yeah, I guess we can remove `QuotedStringConverter` now.

I'll have a look at the `rev` and `rel` parameter types. Splitting them directly could certainly be an option.

Nice catch about the title.

**Pull request merged**
