### PR TITLE
Make sure httpurlconnection-executor treats headers in a case-insenit…

### LINKED ISSUE #30: httpurlconnection-executor headers not case agnostic

### PR DESCRIPTION
**Pull request by dmfs**
…ive manner. fixes #30

Since we get the headers in a Map of Strings we need to take special case to compate header names case-insensitively.

@lemonboston please review.

I know that there a lot of these annoying iml files in the commit.

### CODE REVIEW

**Comment by lemonboston** [comment]
For this case insensitive `Map`, could we create just a `Map` decorator? I suppose that's what is essentially needed here, right?
So instead of the 
```
return new FilteredIterator<>(mConnection.getHeaderFields().keySet().iterator(), new StringEqualsIgnoreCase(headerType.name())).hasNext();
...
Map<String, List<String>> headers = mConnection.getHeaderFields();
        return headerType.entityFromString(headers.get(
                new FilteredIterator<>(headers.keySet().iterator(), new StringEqualsIgnoreCase(headerType.name())).next()).get(0));
```
We could have something like:
```
return new CaseInsensitiveKey(mConnection.getHeaderFields()).containsKey(headerType.name());
...
return headerType.entityFromString(new CaseInsensitiveKey(mConnection.getHeaderFields().get(headerType.name())).get(0));
```
And possibly even more simplificaton in `HttpUrlConnectionHeaders#header(..)`.

The `Map` decorator could contain the same code, but it would be hidden there, and by that removing the code duplication and making easier usage.

Unrelated note: Could we maybe move `AbstractFilteredIterator.IteratorFilter` and `AbstractConvertedIterator.Converter` up to top level, so their usage is shorter, less bloated?
I know we can static import them, but they are also kind of general, it's possible other types could use them, too.

Otherwise I finished the review, although it's quite difficult for me to understand and verify the mentioned `org.dmfs.httpessentials.httpurlconnection.HttpUrlConnectionHeaders#header(org.dmfs.httpessentials.headers.ListHeaderType<T>)` in this form.

**Comment by dmfs** [comment]
I already considered the Map. However, maybe it's better to just remap with lower case keys.

Actually, I've had an idea of how to refactor the entire header thing. When reading response headers it currently looks like this:

```java
List<Link> links = response.headers().header(HttpHeaders.LINK).value();
// or
MediaType contenttype = response.headers().header(HttpHeaders.CONTENT_TYPE).value();
```
So it's sort of a map like interface. Before you do that you always have to check of the existence of the header like to
```java
if (response.headers().contains(HttpHeaders.LINK)) { .... }
```

Instead I could imagine a declarative approach like so
```
// create in Iterable of all Links in the response headers
Iterable<Link> links = new Links(response.headers());
// or
// get the ContentType contained in the headers, providing a default in case no content-type header is present
MediaType contentType = new ContentType(response.headers(), defaultContentType);
```

So essentially create a new class per header type which implements a suitable interface.

Not sure how adding, modifying or removing headers would work with this approach. Also this requires a few breaking API changes.

I guess `Headers` would have an interface like this

```
public interface Headers {
    Iterator<Header> headers(CharSequence headerName);
   // probably more methods to modify the headers
}

// and
public interface Header {
    CharSequence name();
    CharSequence value();
}
```

**Comment by lemonboston** [comment]
I see, and those changes look good to me too as far as I can tell. That `HeaderLine` is quite straightforward, has less conceptual overhead than current types.

Just a note on it: I am wondering if that `contains(..)` call might still be needed for some logic though. It can be replaced  with the `links.hasNext()` and `contentType.equals(defaultContentType)` in your examples, but how about having `isPresent()` method on the new `Header` interface, so all these declaratively created headers could represent absent value as well.

**Comment by lemonboston** [comment]
About the case insensitive map, not certain if it works, so just a tip:
http://stackoverflow.com/questions/8236945/case-insensitive-string-as-hashmap-key
so something like:
```
Map<String, String> caseInsensitiveMap = 
    new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);
caseInsensitiveMap.putAll(connection.getHeaderFields())
```

**Comment by dmfs** [comment]
That wouldn't work for us. A header can be present multiple times with different case. I.e. even if it doesn't make much sense a server could send these headers:

```http
LINK:<http://example.com>; rel="example"
link:<http://example.org>; rel="about"
```
Just copying the map like above would preserve only one of these headers.
We would at the very least have to make sure we append elements if there already is an entry.

**Comment by dmfs** [comment]
I'm merging this now. We'll refactor this when the new Headers interface is ready.

**Pull request merged**
